
'use client';

import { useState, useRef, ChangeEvent } from 'react';
import { useForm, FormProvider } from 'react-hook-form';
import * as z from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  Paperclip,
  Send,
  LoaderCircle,
  Download,
  BookOpenCheck,
  FileText,
  X,
  Sparkles,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { chat } from '@/ai/flows/chat';
import { analyzeUploadedNotes } from '@/ai/flows/analyze-uploaded-notes';
import { generatePersonalizedStudyMaterials, GeneratePersonalizedStudyMaterialsOutput } from '@/ai/flows/generate-personalized-study-materials';
import { jsPDF } from 'jspdf';
import { Separator } from '@/components/ui/separator';

interface Message {
  sender: 'user' | 'ai';
  text: string;
}

interface UploadedFile {
  name: string;
  dataUri: string;
}

const formSchema = z.object({
  prompt: z.string().min(1),
});

export default function DashboardPage() {
  const [messages, setMessages] = useState<Message[]>([
    {
      sender: 'ai',
      text: 'Hello! I am EduVault AI. How can I help you today? Upload your notes to ask questions about them.',
    },
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [uploadedFile, setUploadedFile] = useState<UploadedFile | null>(null);
  const [studyMaterials, setStudyMaterials] = useState<GeneratePersonalizedStudyMaterialsOutput | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      prompt: '',
    },
  });

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = e => {
        const dataUri = e.target?.result as string;
        setUploadedFile({ name: file.name, dataUri });
      };
      reader.readAsDataURL(file);
    }
  };

  const handleFileUploadClick = () => {
    fileInputRef.current?.click();
  };

  const removeFile = () => {
    setUploadedFile(null);
     if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const handleGenerateStudyMaterials = async () => {
    setIsGenerating(true);
    setStudyMaterials(null);
    try {
        const conversationHistory = messages.map(m => `${m.sender}: ${m.text}`).join('\n');
        const materials = await generatePersonalizedStudyMaterials({
            conversationHistory,
            studentName: 'Student' 
        });
        setStudyMaterials(materials);
    } catch (error) {
        console.error("Error generating study materials:", error);
        setMessages(prev => [...prev, {sender: 'ai', text: "Sorry, I had trouble generating the study materials."}]);
    } finally {
        setIsGenerating(false);
    }
  }

  const handleDownloadNotes = () => {
    const doc = new jsPDF();
    const margin = 10;
    let y = 20;

    const addWatermark = () => {
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.setFontSize(50);
        doc.setTextColor(230, 230, 230);
        doc.text('Generated by EduVault AI', pageWidth / 2, pageHeight / 2, {
            align: 'center',
            angle: -45
        });
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
    };

    const checkNewPage = (neededHeight: number) => {
        if (y + neededHeight > 280) {
            doc.addPage();
            addWatermark();
            y = margin;
        }
    };
    
    addWatermark();
    doc.setFontSize(18);
    doc.text("EduVault AI - Study Materials", margin, y);
    y += 15;

    if (studyMaterials) {
        Object.entries(studyMaterials).forEach(([key, value]) => {
            const title = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
            checkNewPage(20);
            doc.setFontSize(16);
            doc.text(title, margin, y);
            y+= 10;
            doc.setFontSize(12);
            
            const textLines = doc.splitTextToSize(value, doc.internal.pageSize.getWidth() - margin * 2);
            checkNewPage(textLines.length * 7);
            doc.text(textLines, margin, y);
            y += textLines.length * 7 + 10;
        });
    } else {
        doc.setFontSize(12);
        doc.text("No study materials generated yet.", margin, y);
    }


    doc.save('eduvault-ai-study-materials.pdf');
  };

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    setStudyMaterials(null);
    const userMessage: Message = { sender: 'user', text: values.prompt };
    setMessages(prev => [...prev, userMessage]);
    form.reset();

    try {
      let aiResponseText: string;
      if (uploadedFile) {
        const aiResponse = await analyzeUploadedNotes({
          notesDataUri: uploadedFile.dataUri,
          question: values.prompt,
        });
        aiResponseText = aiResponse.answer;
      } else {
        const aiResponse = await chat({ prompt: values.prompt });
        aiResponseText = aiResponse.response;
      }
      setMessages(prev => [...prev, { sender: 'ai', text: aiResponseText }]);
    } catch (error) {
      console.error('Error getting AI response:', error);
      setMessages(prev => [
        ...prev,
        { sender: 'ai', text: "Sorry, I'm having trouble responding right now." },
      ]);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="flex flex-col h-screen bg-background">
      <header className="flex items-center justify-between p-4 border-b">
        <div className="flex items-center gap-2">
          <BookOpenCheck className="w-8 h-8 text-primary" />
          <h1 className="text-xl font-bold font-headline">EduVault AI</h1>
        </div>

        <div className="flex items-center gap-4">
           <Button variant="outline" size="sm" onClick={handleGenerateStudyMaterials} disabled={messages.length <= 1 || isLoading || isGenerating}>
            {isGenerating ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
            Generate Study Materials
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownloadNotes} disabled={!studyMaterials}>
            <Download className="mr-2 h-4 w-4" />
            Download Materials
          </Button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto p-4 md:p-6 space-y-4">
        {messages.map((msg, index) => (
          <div
            key={index}
            className={`flex items-start gap-3 ${
              msg.sender === 'user' ? 'justify-end' : ''
            }`}
          >
            {msg.sender === 'ai' && (
              <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center font-bold text-primary text-sm">
                AI
              </div>
            )}
            <Card
              className={`max-w-xl ${
                msg.sender === 'user'
                  ? 'bg-primary text-primary-foreground'
                  : 'bg-card'
              }`}
            >
              <CardContent className="p-3">
                <p>{msg.text}</p>
              </CardContent>
            </Card>
            {msg.sender === 'user' && (
              <div className="w-8 h-8 rounded-full bg-accent/20 flex items-center justify-center font-bold text-accent-foreground text-sm">
                U
              </div>
            )}
          </div>
        ))}
        {isLoading && (
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center font-bold text-primary text-sm">
              AI
            </div>
            <Card className="max-w-xl">
              <CardContent className="p-3 flex items-center gap-2">
                <LoaderCircle className="w-5 h-5 animate-spin" />
                <span>Thinking...</span>
              </CardContent>
            </Card>
          </div>
        )}

        {studyMaterials && (
            <Card className="mt-6">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Sparkles className="text-primary" />
                        Generated Study Materials
                    </CardTitle>
                    <CardDescription>
                        Here are the study materials generated from your conversation. You can download them as a PDF.
                    </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                    {Object.entries(studyMaterials).map(([key, value]) => (
                         <div key={key}>
                            <Separator />
                            <div className="mt-4">
                                <h3 className="font-bold text-lg capitalize mb-2">{key.replace(/([A-Z])/g, ' $1')}</h3>
                                <p className="text-sm text-muted-foreground whitespace-pre-wrap">{value}</p>
                            </div>
                        </div>
                    ))}
                </CardContent>
            </Card>
        )}
      </main>

      <footer className="p-4 border-t bg-background">
        {uploadedFile && (
            <div className="mb-2 p-2 bg-muted rounded-md flex items-center justify-between text-sm">
                <div className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-muted-foreground" />
                    <span className="font-medium truncate max-w-xs">{uploadedFile.name}</span>
                </div>
                <Button variant="ghost" size="icon" onClick={removeFile} className="h-6 w-6">
                    <X className="w-4 h-4" />
                </Button>
            </div>
        )}
        <FormProvider {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="flex items-center gap-2"
          >
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileChange}
              className="hidden"
              accept=".txt,.md,.pdf,.doc,.docx"
            />
            <Button
              variant="ghost"
              size="icon"
              type="button"
              onClick={handleFileUploadClick}
              disabled={isLoading || !!uploadedFile}
            >
              <Paperclip />
            </Button>
            <Input
              autoComplete="off"
              placeholder={uploadedFile ? "Ask a question about your notes..." : "Ask me anything..."}
              {...form.register('prompt')}
              disabled={isLoading || isGenerating}
            />
            <Button
              variant="default"
              size="icon"
              type="submit"
              disabled={isLoading || isGenerating}
            >
              <Send />
            </Button>
          </form>
        </FormProvider>
      </footer>
    </div>
  );
}

    