
'use client';

import { useState, useRef, ChangeEvent } from 'react';
import { useForm, FormProvider } from 'react-hook-form';
import * as z from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  Paperclip,
  Send,
  LoaderCircle,
  Download,
  BookOpenCheck,
  FileText,
  X,
  Sparkles,
  Map,
  FileCode2,
  HelpCircle,
  ListOrdered,
  Award,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { chat, ChatOutput } from '@/ai/flows/chat';
import { analyzeUploadedNotes } from '@/ai/flows/analyze-uploaded-notes';
import { jsPDF } from 'jspdf';
import { useToast } from '@/hooks/use-toast';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';

type Message = {
  sender: 'user';
  text: string;
} | {
  sender: 'ai';
  content: ChatOutput | string; // Can be simple string or complex object
};


interface UploadedFile {
  name: string;
  dataUri: string;
}

const formSchema = z.object({
  prompt: z.string().min(1),
});

export default function DashboardPage() {
  const [messages, setMessages] = useState<Message[]>([
    {
      sender: 'ai',
      content: 'Hello! I am EduVault AI. How can I help you today? For every question, I will generate a complete set of study materials. You can also upload your notes to ask questions about them.',
    },
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const [uploadedFile, setUploadedFile] = useState<UploadedFile | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      prompt: '',
    },
  });

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = e => {
        const dataUri = e.target?.result as string;
        setUploadedFile({ name: file.name, dataUri });
        toast({
            title: "File Uploaded",
            description: `${file.name} is ready. Ask a question about it!`,
        });
      };
      reader.readAsDataURL(file);
    }
  };

  const handleFileUploadClick = () => {
    fileInputRef.current?.click();
  };

  const removeFile = () => {
    setUploadedFile(null);
     if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
    toast({
        title: "File Removed",
        description: "The uploaded file has been removed.",
    });
  };

  const handleDownloadNotes = (materialsToDownload: ChatOutput) => {
    if (!materialsToDownload) {
        toast({
            variant: "destructive",
            title: "Nothing to Download",
            description: "There are no study materials in this message.",
        });
        return;
    };

    const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
    const margin = 10;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const usableWidth = pageWidth - margin * 2;
    let y = 20;

    const addWatermark = () => {
      doc.setFontSize(50);
      doc.setTextColor(220, 220, 220);
      doc.text('Generated by EduVault AI', pageWidth / 2, pageHeight / 2, {
          align: 'center',
          angle: -45
      });
      doc.setTextColor(0, 0, 0); // Reset text color
    };

    const checkNewPage = (neededHeight: number) => {
        if (y + neededHeight > pageHeight - margin) {
            doc.addPage();
            addWatermark();
            y = margin;
        }
    };
    
    // Initial page with watermark
    addWatermark();
    
    doc.setFontSize(22);
    doc.text("EduVault AI - Study Materials", pageWidth / 2, y, { align: 'center' });
    y += 15;

    Object.entries(materialsToDownload).forEach(([key, value]) => {
        const title = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
        
        checkNewPage(12); // Space for title
        doc.setFontSize(16);
        doc.setTextColor(63, 131, 248); // Primary color
        doc.text(title, margin, y);
        y += 8;

        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageWidth - margin, y); // Separator line
        y += 8;
        
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        
        const textLines = doc.splitTextToSize(value, usableWidth);
        
        textLines.forEach((line: string) => {
            checkNewPage(7); // Height for one line
            doc.text(line, margin, y);
            y += 7;
        });

        y += 10; // Extra space between sections
    });

    doc.save('eduvault-ai-study-materials.pdf');
    toast({
      title: "Download Complete",
      description: "Your study materials have been saved as a PDF.",
    });
  };

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    const userMessage: Message = { sender: 'user', text: values.prompt };
    
    // Construct conversation history from previous messages
    const conversationHistory = messages
      .map(m => {
        if (m.sender === 'user') {
          return `User: ${m.text}`;
        } else if (typeof m.content === 'string') {
          return `AI: ${m.content}`;
        }
        // For complex AI content, we'll just summarize it for history context
        return `AI: [Generated Study Materials]`;
      })
      .join('\n');

    setMessages(prev => [...prev, userMessage]);
    form.reset();

    try {
      let aiResponse: Message;
      if (uploadedFile) {
        // The analyzeUploadedNotes flow returns a simple answer. We'll wrap it for consistency.
        const response = await analyzeUploadedNotes({
          notesDataUri: uploadedFile.dataUri,
          question: values.prompt,
        });
        aiResponse = { sender: 'ai', content: response.answer };
      } else {
        // The main chat flow returns the detailed study materials object.
        const response = await chat({ prompt: values.prompt, conversationHistory });
        aiResponse = { sender: 'ai', content: response };
      }
      setMessages(prev => [...prev, aiResponse]);
    } catch (error) {
      console.error('Error getting AI response:', error);
      setMessages(prev => [
        ...prev,
        { sender: 'ai', content: "Sorry, I'm having trouble responding right now." },
      ]);
    } finally {
      setIsLoading(false);
    }
  }

  const studyMaterialSections = [
    { key: 'mindMap', title: 'Mind Map', icon: Map, color: 'text-blue-500' },
    { key: 'revisionNotes', title: 'Revision Notes', icon: FileCode2, color: 'text-green-500' },
    { key: 'questionsAndAnswers', title: 'Q&A for Self-Assessment', icon: HelpCircle, color: 'text-yellow-500' },
    { key: 'keywords', title: 'Keywords & Definitions', icon: ListOrdered, color: 'text-purple-500' },
    { key: 'cbseMarkingScheme', title: 'CBSE Marking Scheme', icon: Award, color: 'text-red-500' },
  ];

  const renderAiMessage = (content: ChatOutput | string) => {
    if (typeof content === 'string') {
      return <p className="whitespace-pre-wrap">{content}</p>;
    }
    
    return (
      <div className="space-y-4">
        {studyMaterialSections.map(section => {
          const sectionContent = content[section.key as keyof ChatOutput];
          if (!sectionContent) return null;

          const Icon = section.icon;

          return (
            <Card key={section.key} className="bg-card/50 overflow-hidden">
              <CardHeader className="flex flex-row items-center gap-3 p-4 bg-muted/50 border-b">
                <Icon className={`w-6 h-6 ${section.color}`} />
                <CardTitle className="text-lg">{section.title}</CardTitle>
              </CardHeader>
              <CardContent className="p-4 prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap">
                {sectionContent}
              </CardContent>
            </Card>
          );
        })}
      </div>
    );
  };


  return (
    <div className="flex flex-col h-screen bg-background">
      <header className="flex items-center justify-between p-4 border-b">
        <div className="flex items-center gap-2">
          <BookOpenCheck className="w-8 h-8 text-primary" />
          <h1 className="text-xl font-bold font-headline">EduVault AI</h1>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto p-4 md:p-6 space-y-4">
        {messages.map((msg, index) => (
          <div
            key={index}
            className={`flex items-start gap-3 ${
              msg.sender === 'user' ? 'justify-end' : ''
            }`}
          >
            {msg.sender === 'ai' && (
              <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center font-bold text-primary text-sm flex-shrink-0">
                AI
              </div>
            )}
            <Card
              className={`max-w-2xl w-full ${
                msg.sender === 'user'
                  ? 'bg-primary text-primary-foreground'
                  : 'bg-card'
              }`}
            >
              <CardContent className="p-3">
                {msg.sender === 'user' ? <p className="whitespace-pre-wrap">{msg.text}</p> : renderAiMessage(msg.content)}
                 {msg.sender === 'ai' && typeof msg.content !== 'string' && (
                  <div className="mt-4 flex justify-end">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleDownloadNotes(msg.content as ChatOutput)}
                    >
                      <Download className="mr-2 h-4 w-4" />
                      Download PDF
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
            {msg.sender === 'user' && (
              <div className="w-8 h-8 rounded-full bg-accent/20 flex items-center justify-center font-bold text-accent-foreground text-sm flex-shrink-0">
                U
              </div>
            )}
          </div>
        ))}
        {isLoading && (
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center font-bold text-primary text-sm flex-shrink-0">
              AI
            </div>
            <Card className="max-w-xl">
              <CardContent className="p-3 flex items-center gap-2">
                <LoaderCircle className="w-5 h-5 animate-spin" />
                <span>Thinking...</span>
              </CardContent>
            </Card>
          </div>
        )}
      </main>

      <footer className="p-4 border-t bg-background">
        {uploadedFile && (
            <div className="mb-2 p-2 bg-muted rounded-md flex items-center justify-between text-sm">
                <div className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-muted-foreground" />
                    <span className="font-medium truncate max-w-xs">{uploadedFile.name}</span>
                </div>
                <Button variant="ghost" size="icon" onClick={removeFile} className="h-6 w-6">
                    <X className="w-4 h-4" />
                </Button>
            </div>
        )}
        <FormProvider {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="flex items-center gap-2"
          >
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileChange}
              className="hidden"
              accept=".txt,.md,.pdf,.doc,.docx"
            />
             <TooltipProvider>
                <Tooltip>
                    <TooltipTrigger asChild>
                        <Button
                          variant="ghost"
                          size="icon"
                          type="button"
                          onClick={handleFileUploadClick}
                          disabled={isLoading || !!uploadedFile}
                        >
                          <Paperclip />
                        </Button>
                    </TooltipTrigger>
                    <TooltipContent>
                        <p>Upload a file to ask questions about it.</p>
                    </TooltipContent>
                </Tooltip>
            </TooltipProvider>
            <Input
              autoComplete="off"
              placeholder={uploadedFile ? "Ask a question about your notes..." : "Ask me anything to get study materials..."}
              {...form.register('prompt')}
              disabled={isLoading}
            />
            <Button
              variant="default"
              size="icon"
              type="submit"
              disabled={!form.watch('prompt') || isLoading}
            >
              <Send />
            </Button>
          </form>
        </FormProvider>
      </footer>
    </div>
  );
